AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Training For RDS

Parameters:
  RDSMasterUsername:
    Type: String
    Description: The database admin account name
    Default: admin
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '^[a-zA-Z0-9]*' 
  RDSMasterUserPassword:
    Type: String
    Description: The database admin account password
    MinLength: 8
    AllowedPattern: '^[a-zA-Z0-9]*$' 
    NoEcho: true
  RDSDBName:
    Type: String
    Description: The database name
    Default: test_db
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '^[a-zA-Z0-9_]*$' 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Input parameters
        Parameters:
          - RDSMasterUsername
          - RDSMasterUserPassword
          - RDSDBName

Resources:
  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
        DBSubnetGroupDescription: 'This is RdsSubnetGroup'
        DBSubnetGroupName: RdsSubnetGroup
        SubnetIds: 
          -  !ImportValue PrivateSubnet1
          -  !ImportValue PrivateSubnet2
                  
        Tags: 
          - Key: Name
            Value: RdsSubnetGroup

  MyRDSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for RDS instance
      SecurityGroupEgress: 
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue MyEC2SecurityGroup
      VpcId: !ImportValue CFnVPC

  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: training-db-instance
      DBSubnetGroupName: RdsSubnetGroup
      Engine: mysql
      MasterUsername: !Ref RDSMasterUsername
      MasterUserPassword: !Ref RDSMasterUserPassword
      DBName: !Ref RDSDBName
      StorageType: gp3
      MultiAZ: true
      Tags:
        - Key: Name
          Value: StudyRDSInstance
      VPCSecurityGroups: 
        - !Ref MyRDSSecurityGroup 
        
    DependsOn: RdsSubnetGroup

Outputs:
  RDSEndpoint:
    Value: !GetAtt MyRDSInstance.Endpoint.Address

  RDSUsername:
    Value: !Ref RDSMasterUsername

  RDSDBName:
    Value: !Ref RDSDBName